language: julia
os: linux
dist: bionic

julia:
    - 1

addons:
    apt:
        packages:
            - python3-pip
            - python3-setuptools


before_script:
    - export PATH=$HOME/.local/bin:$PATH

script:
    - julia --color=yes -e 'using Pkg; pkg"add Optim; add SpecialFunctions; precompile;"'
    - ./test/travis.sh
