language: julia
julia:
    - 1

jobs:
  include:
    - name: "Linux"
      os: linux
      dist: bionic
      before_install: sudo apt-get -y install python3-pip python3-setuptools
    - name: "macOS"
      os: osx
      before_install: python3 --version; pip3 --version; sw_vers
    - name: "Windows"
      os: windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
  allow_failures:
    - os: linux
    - os: windows

install: pip3 install --upgrade pip

before_script:
    - julia --color=yes -e 'using Pkg; pkg"add Optim; add SpecialFunctions; precompile;"'

script:
    - pip3 install numpy pandas
    - python3 setup.py install --user
    - PATH=$HOME/.local/bin:$PATH python3 test/test.py

