language: julia
julia:
    - 1
env:
    - PY=python3
    - PATH=$HOME/.local/bin:$PATH

jobs:
  include:
    - name: "Linux"
      os: linux
      before_install: sudo apt-get -y install python3-pip python3-setuptools
    - name: "macOS"
      os: osx
      before_install: python3 --version; pip3 --version; sw_vers
    - name: "Windows"
      os: windows
      before_install:
        - choco install python
        - python -m ensurepip
        - python -m pip install --upgrade pip
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - PY=python
  allow_failures:
  - os: linux
  - os: windows

before_script:

script:
    - julia --color=yes -e 'using Pkg; pkg"add Optim; add SpecialFunctions; precompile;"'
    - $PY -m pip install numpy pandas
    - $PY setup.py install
    - $PY test/test.py

