language: julia
julia:
    - 1

jobs:
  include:
    - name: "Linux"
      os: linux
      dist: bionic
      before_install: sudo apt-get -y install python3-pip python3-setuptools
      env: PY=python3 SETUPPREFIX="--user"
    - name: "Windows"
      os: windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH PY=python

install: pip3 install --upgrade pip

before_script:
    - julia --color=yes -e 'using Pkg; pkg"add Optim; add SpecialFunctions; precompile;"'

script:
    - pip3 install numpy pandas
    - $PY setup.py install $SETUPPREFIX
    - PATH=$HOME/.local/bin:$PATH $PY test/test.py

