site_name: PySR
theme:
  name: material
  palette:
    # Light mode:
    - scheme: pysr
  logo: assets/pysr_logo_reduced.svg
  icon:
    repo: fontawesome/brands/github-alt

extra:
  homepage: https://astroautomata.com/PySR

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/MilesCranmer/PySR

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [pysr]
          options:
            # https://mkdocstrings.github.io/python/usage/#finding-modules
            docstring_style: numpy
            merge_init_into_class: True
            # docstring_options
            separate_signature: True
