site_name: PySR
theme:
  name: material
  palette:
    # Light mode:
    - scheme: pysr
  logo: assets/pysr_logo.svg
  icon:
    repo: fontawesome/brands/github-alt

extra:
  homepage: https://astroautomata.com/PySR

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/MilesCranmer/PySR