[tool.poetry]
name = "pysr"
version = "0.12.0"
description = "Simple and efficient symbolic regression"
authors = ["MilesCranmer <miles.cranmer@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
sympy = "^1.0.0"
numpy = "^1.20.0"
scikit-learn = "^1.0.0"
pandas = "^1.0.0"
julia = "^0.6.0"

[tool.poetry.group.dev.dependencies]
black = "^21.0.0"
ipython = "^8.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
