[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pysr"
version = "1.0.0"
authors = [
    {name = "Miles Cranmer", email = "miles.cranmer@gmail.com"},
]
description = "Simple and efficient symbolic regression"
readme = {file = "README.md", content-type = "text/markdown"}
license = {file = "LICENSE"}
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: Apache Software License"
]
dependencies = [
    "sympy>=1.0.0,<2.0.0",
    "pandas>=0.21.0,<3.0.0",
    "numpy>=1.13.0,<3.0.0",
    "scikit_learn>=1.0.0,<2.0.0",
    "juliacall==0.9.23",
    "click>=7.0.0,<9.0.0",
    "setuptools>=50.0.0",
    "typing-extensions>=4.0.0,<5.0.0",
]

[tool.setuptools]
packages = ["pysr", "pysr._cli", "pysr.test"]
include-package-data = false
package-data = {pysr = ["juliapkg.json"]}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}

[tool.isort]
profile = "black"

[tool.rye]
dev-dependencies = [
    "pre-commit>=3.7.0",
    "ipython>=8.23.0",
    "ipykernel>=6.29.4",
    "mypy>=1.10.0",
    "jax[cpu]>=0.4.26",
    "torch>=2.3.0",
    "pandas-stubs>=2.2.1.240316",
    "types-pytz>=2024.1.0.20240417",
    "types-openpyxl>=3.1.0.20240428",
    "coverage>=7.5.3",
    "pytest>=8.3.3",
    "nbval>=0.11.0",
]
