name: Apptainer

on:
  push:
    branches:
      - 'master'
    paths:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'master'
    paths:
      - '**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: eWaterCycle/setup-apptainer@v2
        with:
            apptainer-version: 1.3.0
      - name: Build apptainer
        run: apptainer build --notest pysr.sif Apptainer.def
      - name: Create test directory
        run: |
          mkdir test.d && cp pysr.sif test.d
      - name: Test apptainer
        run: |
          cd test.d
          apptainer test ./pysr.sif
