name: Apptainer

on:
  push:
    branches:
      - 'master'
    paths:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'master'
    paths:
      - '**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: ['linux/amd64']

    steps:
      - uses: actions/checkout@v4
      - uses: eWaterCycle/setup-apptainer@v2
        with:
            apptainer-version: 1.3.0
      - name: Build apptainer
        run: apptainer build pysr.sif Apptainer.def
      - name: Test apptainer
        run: apptainer exec ./pysr.sif /bin/bash -c 'pip install pytest nbval && PYTHONPATH=/pysr:/pysr/pysr python3 -m pysr test main,cli,startup'
