name: conda-forge

# This CI tries the conda-forge version of PYSR

on:
  schedule:
    # Run at the 0th minute of the 10th hour (UTC).
    # This means the job will run at 5am EST.
    - cron: "0 10 * * *"
    # This will automatically run on master branch only.
  workflow_dispatch:

jobs:
  conda_test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9']
        os: ['ubuntu-latest', 'macos-latest']
    
    steps:
      - uses: actions/checkout@v2
      - name: "Set up conda"
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
      - name: "Install pysr with conda"
        run: conda create -n test -c conda-forge python=${{ matrix.python-version }} pysr
      - name: "Run tests"
        run: conda activate test && python3 -m unittest test.test && python3 -m unittest test.test_env