name: docs

on:
  push:
    branches:
      - 'master'
    paths:
      - 'pysr/**'
      - '.github/workflows/docs.yml'
      - 'docs/**'
      - 'setup.py'
      - 'README.md'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Python"
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: "Install packages for docs building"
        run: pip install mkdocs-material mkdocs-autorefs 'mkdocstrings[python]'
      - name: "Build API docs"
        run: cd docs && ./gen_docs.sh
      - name: "Deploy documentation"
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: docs